image: python:3.11


stages:
  - test
  - build
  - push


variables:
  GITLAB_REGISTRY_URL: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi"


before_script:
  - pip install --upgrade pip


mypy:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - mypy proxmoxtemplates


build:
  stage: build
  before_script:
    - export PACKAGE_VERSION="0.1.${CI_PIPELINE_IID}"
    - echo "Setting package version to $PACKAGE_VERSION"
  script:
    - pip install build
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz


deployInGitlab:
  stage: push
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url $GITLAB_REGISTRY_URL dist/* --verbose


deployPublic:
  stage: push
  when: manual
  script:
    - pip install twine
    - twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
