image: python:3.11


stages:
  - build
  - push


variables:
  GITLAB_REGISTRY_URL: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi"


before_script:
  - pip install --upgrade pip


build:
  stage: build
  script:
    - pip install build
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz


deploy:
  stage: push
  script:
    - pip install twine
    - twine upload --repository-url $GITLAB_REGISTRY_URL dist/* -u $CI_JOB_TOKEN -p $CI_JOB_TOKEN


